# Conda environment file for gromacs surface creation
# Author: Alec Glisman (GitHub: @alec-glisman)
# Date: 2023-12-14
#
# Create environment with: $ conda env create -f requirements.yml
# Update environment with: $ conda env update --prune -f requirements.yml
# Remove environment with: $ conda env remove -n pymatgen
#
# Notes:
# - We recommend using mamba instead of conda as the solver for faster
#  environment creation. To do this, run:
#  $ conda install -n base conda-libmamba-solver
#  $ conda config --set solver libmamba

name: pymatgen
channels:
  - conda-forge
dependencies:
  - pip
  # data analysis
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - pyarrow
  # MD packages
  - mdanalysis>=2.6.0
  - mdanalysistests
  - pymatgen
  - openbabel
  - rdkit
  - gromacswrapper
  # plotting
  - matplotlib
  - seaborn
  - colorcet
  - cmasher
  # Jupyter notebooks
  - ipykernel
  - ipywidgets
  - ipympl
  - pandoc
  - notebook
  - jupyter_client
  # testing
  - pytest
  - pytest-cov
  - coverage
  - pre-commit
  # formatting
  - autopep8
  - black
  - flake8
  - pylint
